version: '3.9'

services:
  api:
    build: .
    container_name: numerology_api
    ports:
      - '8000:8000'
    environment:
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_DB: "${DBNAME}"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_DB: "${DBNAME}"
