version: '3.9'

services:
  api:
    build: .
    env_file:
    - .env
    container_name: numerology_api
    ports:
      - '8000:8000'
    environment:
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_DB: "${DBNAME}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_DB: "${DBNAME}"
